app_dir: /opt/apps/hdfs-anomaly

api_image: ghcr.io/andrewb-codes/hdfs-log-anomaly-detection-api
frontend_image: ghcr.io/andrewb-codes/hdfs-log-anomaly-detection-frontend
app_image_tag: main

api_image_ref: "{{ api_image }}:{{ app_image_tag }}"
frontend_image_ref: "{{ frontend_image }}:{{ app_image_tag }}"

docker_public_network: web
frontend_network_alias: hdfs-anomaly-frontend

s3_endpoint_url: https://s3.ru-7.storage.selcloud.ru
s3_region: ru-7
s3_bucket: hdfs-anomaly-artifacts-prod
s3_prefix: prod

app_env:
  DATABASE_URL: postgresql+asyncpg://anomaly_user:{{ postgres_password | urlencode }}@postgres:5432/anomaly
  JWT_SECRET: "{{ jwt_secret }}"
  POSTGRES_DB: anomaly
  POSTGRES_USER: anomaly_user
  POSTGRES_PASSWORD: "{{ postgres_password }}"

  BOOTSTRAP_ADMIN_ENABLED: "true"
  BOOTSTRAP_ADMIN_EMAIL: admin@example.com
  BOOTSTRAP_ADMIN_PASSWORD: "{{ bootstrap_admin_password }}"

  DEMO_USER_ENABLED: "true"
  DEMO_EMAIL: demo@example.com
  DEMO_PASSWORD: "{{ demo_password }}"
