"""create initial schema

Revision ID: c7f65290acad
Revises:
Create Date: 2026-07-09 09:28:09.962876

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7f65290acad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="status"),
            server_default="INACTIVE",
            nullable=False,
        ),
        sa.Column(
            "role", sa.Enum("ADMIN", "USER", name="role"), server_default="USER", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_email"), "profile", ["email"], unique=True)
    op.create_table(
        "request_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("profile_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("block_id", sa.String(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("processing_ms", sa.Float(), nullable=False),
        sa.Column("num_log_lines", sa.Integer(), nullable=True),
        sa.Column("num_events", sa.Integer(), nullable=True),
        sa.Column("num_windows", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("is_anomaly", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_history_profile_id"), "request_history", ["profile_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_history_profile_id"), table_name="request_history")
    op.drop_table("request_history")
    op.drop_index(op.f("ix_profile_email"), table_name="profile")
    op.drop_table("profile")
    sa.Enum(name="role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
